### ISSUE TITLE
พูดคุยเกี่ยวกับโครงงาน

### ISSUE THREAD

**Issue by NongFirstTH** [NongFirstTH/CPE103-project-group-26#1]

**Comment by jejeeii** [comment]
jejee designer

**Comment by NongFirstTH** [comment]
ผมเป็นmanagerนะครับจุ๊บๆ

**Comment by Yamami1221** [comment]
ผมคงเป็นProgrammerสินะ

**Comment by GOLF2546** [comment]
กอล์ฟ Tester

**Comment by NongFirstTH** [comment]
รายละเอียดโปรเจค
-เกมวิ่งแข่งสูตรคูณ
-ผู้เล่น2คนผลัดกันตอบสูตรคูณ มีเวลากำหนดแต่ละคน ตอบถูกเพิ่มคะแนน1แต้มและเดินหน้า ตอบผิดถอยหลังลบคะแนนลง1 เล่นไปเรื่อยๆจนถึงเส้นชัย
