### ISSUE TITLE
วางแผนออกแบบเกมและภาพร่างหน้าตาของเกม

### ISSUE THREAD

**Issue by NongFirstTH** [NongFirstTH/CPE103-project-group-26#2]
-ออกแบบกำหนดหน้าตาของเกม ลักษณะต่างๆในเกม
-ออกแบบภาพร่างหน้าตาเกมเพย์

**Comment by jejeeii** [comment]
![92188069-3A35-465B-A056-9A2ADDD0C4CA](https://user-images.githubusercontent.com/93752490/185735763-f3c7e5b9-6b2b-4da4-9cbb-f45fed26e4da.png)
![C3AAE9CE-AF8C-4F3C-9C54-84284D8BA74B](https://user-images.githubusercontent.com/93752490/185735765-d4334fea-d470-466b-9813-50bd6e256319.png)
![30EA6910-BF39-451F-B4B2-92649B6F8DAF](https://user-images.githubusercontent.com/93752490/185735766-417e1eed-c9f1-4137-843e-d16cf78b0928.png)

**Comment by GOLF2546** [comment]
![BG2](https://user-images.githubusercontent.com/104701283/185748350-d6e8d705-1c9f-4d0e-965b-f1003c7c4616.png)
![raccoon](https://user-images.githubusercontent.com/104701283/185748371-4d5dcf8b-2719-4e1e-8937-0649258ab9d6.png)
![tiger](https://user-images.githubusercontent.com/104701283/185748375-d4ef3f38-6509-47f7-a023-e82bf7100770.png)
เผื่อสนใจ หน้าตาเหมือนกระดานงูพอดี

**Comment by GOLF2546** [comment]
![RUNTOD-LOGO](https://user-images.githubusercontent.com/104701283/185750845-ec17e07b-9b39-49e4-b692-be5f1d23362c.png)

LOGO เปลี่ยนตัวละครค่อยเปลี่ยนก็ได้

**Comment by GOLF2546** [comment]
![RUNTOD-LOGO2](https://user-images.githubusercontent.com/104701283/185751194-41eb40aa-1854-434d-8fbc-e1cf942b9d79.png)
LOGO ตัวละครค่อยเปลี่ยนตอนเลือกตัวละครได้

**Comment by GOLF2546** [comment]
![RUNTOD-LOGO2](https://user-images.githubusercontent.com/104701283/185751236-53e11201-a4ce-4909-b002-da257b89428f.png)
LOGO ค่อยเปลี่ยนตัวละครหลังเลือกตัวละครเสร็จ

**Comment by GOLF2546** [comment]
![RUNTOD__2LOGO](https://user-images.githubusercontent.com/104701283/185751389-8a2899a9-45ee-4207-84db-e61093d8eba0.png)
LOGO เลือกตัวละครได้ค่อยเปลี่ยน

**Comment by jejeeii** [comment]
![2DA64FE1-FE76-4C75-B323-ED14501B484C](https://user-images.githubusercontent.com/93752490/185755302-475ecda7-2dac-4b76-8831-ce7a85ee059a.png)
![C0A3B3F8-D8B8-4512-93DF-03AE24EDF4B3](https://user-images.githubusercontent.com/93752490/185755311-6f522f86-c8bd-4bb0-8df0-4d0a0d9d54d1.png)

**Comment by jejeeii** [comment]
![F33C4043-7C18-4F7C-9D50-1152580BBB9F](https://user-images.githubusercontent.com/93752490/185755333-05bf01bc-ab83-44a5-bdbd-1c6ced810f3d.png)
![8B887E23-D095-49A6-89FA-C4FBBC8D1B9E](https://user-images.githubusercontent.com/93752490/185755335-1cc4bed0-faec-4fb0-969b-102eb5a142e8.png)

**Comment by jejeeii** [comment]
#
