### ISSUE TITLE
สร้างเกม

### ISSUE THREAD

**Issue by NongFirstTH** [NongFirstTH/CPE103-project-group-26#3]
สิ่งที่เกมต้องมี
1.หน้าเข้าเกม
2.score & time
3.การเดินพื้นฐาน
4.turn base
5.ด่านพิเศษ
6.อุปสรรคและไอเท็มพิเศษ
7.หน้าจบเกม

**Comment by Yamami1221** [comment]
ตอนนี้เขียนMenuกับเปายิงฉุบก่อนเริ่มเกมคร่าวๆเสร็จแล้วนะ

**Comment by NongFirstTH** [comment]
อันนี้ส่วนของ turn base กับเดินธรรมดายังไม่ใส่กับดัก
https://scratch.mit.edu/projects/729112796/editor/

**Comment by Yamami1221** [comment]
ต้องตัดระบบจับเวลาออก ไม่สามารถทำได้

**Comment by Yamami1221** [comment]
สามารถสร้างระบบจับเวลาได้แล้ว หลังจากแก้บัคเมื่อคืนที่ตัวละครไม่สามารถเดินได้

**Comment by Yamami1221** [comment]
ระบบscoreสร้างเสร็จแล้ว

**Comment by Yamami1221** [comment]
ด่านพิเศษเสร็จ

**Comment by Yamami1221** [comment]
https://scratch.mit.edu/projects/734398369 เสร็จแล้วครับ
