### ISSUE TITLE
ทดสอบและทดลองเล่นเกม

### ISSUE THREAD

**Issue by NongFirstTH** [NongFirstTH/CPE103-project-group-26#4]

**Comment by GOLF2546** [comment]
https://scratch.mit.edu/projects/729112796/editor/ การทดสอบครั้งที่ 1 ส่วนของ turnbase สามารถทำงานได้ปกติ ยังไม่มีการเข้าด่านพิเศษกับดักหรือฟังก์ชันอื่นๆ

**Comment by GOLF2546** [comment]
https://scratch.mit.edu/projects/730602502?fbclid=IwAR30F8ZuyInmT-hJt7RrRUBiBMh0VJYNiLuW64CJjvIs6IHxHavpjAKwxD4 การทดสอบครั้งที่ 2 การเข้าตอบคำถามด่านพิเศษการเดินเข้าเดินออกจากด่านพิเศษ การ Turnbase หลังจากออกจากด่านพิเศษ ระบบเป่ายิ้งชุบ เพื่อหาผู้เริ่มเล่นก่อน ทำงานได้ปกติ เหลือการนำกับดักใส่และทดสอบเกม หลังจากเสร็จสิ้นเพื่อใช้ในการนำเสนอส่งงาน

**Comment by GOLF2546** [comment]
https://scratch.mit.edu/projects/730902006 การทำสอบครั้งที่ 3 ระบบจับเวลาการเดินการเคลื่อนที่เข้าด่านพิเศษคำถามด่านพิเศษ ระบบเป่ายิ้งชุบ ภายในเกม ทำงานได้ตามปกติ

**Comment by GOLF2546** [comment]
https://scratch.mit.edu/projects/734398369 การทดสอบงานครั้งที่ 4 ทดสอบหน้าผู้ชนะ ปุ่มต่างๆในเกม การเดินเกมของตัวละคร การทำงานของกับดัก การถอยหลังของการโดนกับดัก

**Comment by GOLF2546** [comment]
https://scratch.mit.edu/projects/734398369 เกมสมบูรณ์ตามที่ต้องการ

**Comment by GOLF2546** [comment]
https://scratch.mit.edu/projects/734703667 พบบัคการเดินหลังจากถอยหลังเมื่อตอบหลอดไฟผิด แก้แล้ว

**Comment by GOLF2546** [comment]
https://scratch.mit.edu/projects/734703667 สมบูรณ์ที่สุดในทั้งหมด
