### ISSUE TITLE
ออกแบบTemplateนำเสนอโครงงาน

### ISSUE THREAD

**Issue by NongFirstTH** [NongFirstTH/CPE103-project-group-26#5]

**Comment by NongFirstTH** [comment]
https://docs.google.com/presentation/d/1Bkii2R-rOetYoVrNDl4gAucauh4pyq-ZOgE4tqvFj3I/edit?usp=sharing

**Comment by NongFirstTH** [comment]
-เพิ่มความสนุกของเกม
-ช่องแต่ละช่องไม่ควรว่างเกินไป

**Comment by jejeeii** [comment]
<img width="960" alt="B08B88B6-86EA-422A-8D1E-AF58F6B81249" src="https://user-images.githubusercontent.com/93752490/191318303-3e59858f-f5ce-49cd-892c-75ca136707e5.png">
<img width="960" alt="9DBA86C4-F2AF-4B86-A3C1-559EABFEFDB5" src="https://user-images.githubusercontent.com/93752490/191318332-772116cc-76a2-433b-9e59-141d0fab4a8b.png">
<img width="960" alt="EF1327F3-4280-422E-A693-2005F8C2A8AF" src="https://user-images.githubusercontent.com/93752490/191318334-b47c76cb-1d18-473f-b500-4e637d539591.png">
